### ISSUE TITLE
Star를 누른적이 없습니다.

### ISSUE THREAD

**Issue by KimGenius** [KSH-code/TIL#1]
안녕하세요?

저는 스타를 누른적이 없는데 스타가 되어있네요.
이 부분 해결해주시길 바랍니다.

감사합니다.

**Comment by KimGenius** [comment]
2일이 지났는데 이슈 해결을 안해주시네요.
불친절해서 별점 1점 남기고 갑니다.

**Comment by KimGenius** [comment]
⭐️

**Comment by KSH-code** [comment]
해결 완료.

**Comment by KimGenius** [comment]
도대체 어느 부분이 해결된건지 모르겠네요 신고하겠습니다.
